/* hk_aqhi.js — GENERATED by scripts/ingest_aqhi.py. Do not edit by hand.
 * EPD publishes AQHI hourly; this file is refreshed hourly by Actions.
 * The page shows recordTime so any staleness is visible, never hidden. */
const HK_AQHI = {
  "generatedAt": "2026-08-13T08:40:27+00:00",
  "recordTime": "Thu, 13 Aug 2026 16:30",
  "source": "EPD aqhi.gov.hk RSS (CORS-locked; ingested hourly by GitHub Actions)",
  "stations": [
    {
      "name": "Central/Western",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Southern",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Eastern",
      "type": "general",
      "aqhi": "4",
      "risk": "Moderate"
    },
    {
      "name": "Kwun Tong",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Sham Shui Po",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Kwai Chung",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Tsuen Wan",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Tseung Kwan O",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Yuen Long",
      "type": "general",
      "aqhi": "4",
      "risk": "Moderate"
    },
    {
      "name": "Tuen Mun",
      "type": "general",
      "aqhi": "4",
      "risk": "Moderate"
    },
    {
      "name": "Tung Chung",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Tai Po",
      "type": "general",
      "aqhi": "4",
      "risk": "Moderate"
    },
    {
      "name": "Sha Tin",
      "type": "general",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "North",
      "type": "general",
      "aqhi": "4",
      "risk": "Moderate"
    },
    {
      "name": "Tap Mun",
      "type": "general",
      "aqhi": "4",
      "risk": "Moderate"
    },
    {
      "name": "Causeway Bay",
      "type": "roadside",
      "aqhi": "4",
      "risk": "Moderate"
    },
    {
      "name": "Central",
      "type": "roadside",
      "aqhi": "3",
      "risk": "Low"
    },
    {
      "name": "Mong Kok",
      "type": "roadside",
      "aqhi": "3",
      "risk": "Low"
    }
  ]
};
