/* hk_tctrack.js — GENERATED by scripts/ingest_tctrack.py. Do not edit by hand.
 * HKO updates TC forecast tracks 3-hourly (6-hourly for distant systems);
 * this file is refreshed every 30 minutes by Actions, commit-only-on-change.
 * storms: [] means HKO currently issues no forecast track — a real answer.
 * The page shows bulletinTime and generatedAt separately: staleness is
 * always visible, never hidden. */
const HK_TCTRACK = {
  "generatedAt": "2026-08-28T17:41:10+00:00",
  "source": "HKO tc_list.xml + hko_tctrack_{TCID}.xml on www.weather.gov.hk (no CORS headers; ingested every 30 min by GitHub Actions)",
  "storms": [
    {
      "id": "2630",
      "nameEn": "SAUDEL",
      "nameZh": "沙德爾",
      "bulletinTime": "2026-08-28T21:56:45+08:00",
      "analysis": {
        "lat": 27.4,
        "lon": 118.3,
        "time": "2026-08-28T12:00:00+00:00",
        "intensity": "Tropical Storm",
        "wind": "65km/h"
      },
      "past": [
        {
          "i": 1,
          "lat": 19.5,
          "lon": 144.9,
          "time": "2026-08-22T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 2,
          "lat": 20.4,
          "lon": 143.7,
          "time": "2026-08-22T18:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 3,
          "lat": 21.0,
          "lon": 142.4,
          "time": "2026-08-23T00:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 4,
          "lat": 21.8,
          "lon": 141.0,
          "time": "2026-08-23T06:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 5,
          "lat": 22.5,
          "lon": 139.5,
          "time": "2026-08-23T12:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 6,
          "lat": 23.2,
          "lon": 137.9,
          "time": "2026-08-23T18:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 7,
          "lat": 24.0,
          "lon": 136.5,
          "time": "2026-08-24T00:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 8,
          "lat": 24.5,
          "lon": 134.8,
          "time": "2026-08-24T06:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 9,
          "lat": 24.9,
          "lon": 133.5,
          "time": "2026-08-24T12:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 10,
          "lat": 25.5,
          "lon": 132.2,
          "time": "2026-08-24T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 11,
          "lat": 26.1,
          "lon": 131.2,
          "time": "2026-08-25T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 12,
          "lat": 26.8,
          "lon": 130.1,
          "time": "2026-08-25T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 13,
          "lat": 27.1,
          "lon": 129.1,
          "time": "2026-08-25T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 14,
          "lat": 27.5,
          "lon": 128.1,
          "time": "2026-08-25T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 15,
          "lat": 27.9,
          "lon": 127.2,
          "time": "2026-08-26T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 16,
          "lat": 28.4,
          "lon": 126.7,
          "time": "2026-08-26T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 17,
          "lat": 28.6,
          "lon": 125.9,
          "time": "2026-08-26T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 18,
          "lat": 28.6,
          "lon": 125.3,
          "time": "2026-08-26T18:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "145km/h"
        },
        {
          "i": 19,
          "lat": 28.6,
          "lon": 125.0,
          "time": "2026-08-26T21:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "145km/h"
        },
        {
          "i": 20,
          "lat": 28.6,
          "lon": 124.9,
          "time": "2026-08-27T00:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "145km/h"
        },
        {
          "i": 21,
          "lat": 28.6,
          "lon": 124.6,
          "time": "2026-08-27T03:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "145km/h"
        },
        {
          "i": 22,
          "lat": 28.5,
          "lon": 124.2,
          "time": "2026-08-27T06:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "145km/h"
        },
        {
          "i": 23,
          "lat": 28.4,
          "lon": 123.9,
          "time": "2026-08-27T09:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 24,
          "lat": 28.1,
          "lon": 123.5,
          "time": "2026-08-27T12:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 25,
          "lat": 28.0,
          "lon": 123.1,
          "time": "2026-08-27T15:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 26,
          "lat": 28.1,
          "lon": 122.6,
          "time": "2026-08-27T18:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 27,
          "lat": 28.2,
          "lon": 121.9,
          "time": "2026-08-27T21:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 28,
          "lat": 28.2,
          "lon": 121.3,
          "time": "2026-08-28T00:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "130km/h"
        },
        {
          "i": 29,
          "lat": 27.8,
          "lon": 120.5,
          "time": "2026-08-28T03:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "110km/h"
        },
        {
          "i": 30,
          "lat": 27.6,
          "lon": 120.0,
          "time": "2026-08-28T06:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "105km/h"
        },
        {
          "i": 31,
          "lat": 27.4,
          "lon": 119.3,
          "time": "2026-08-28T09:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        }
      ],
      "forecast": [
        {
          "i": 1,
          "lat": 27.43,
          "lon": 118.13
        },
        {
          "i": 2,
          "lat": 27.47,
          "lon": 117.89
        },
        {
          "i": 3,
          "lat": 27.51,
          "lon": 117.61
        },
        {
          "i": 4,
          "lat": 27.56,
          "lon": 117.31
        },
        {
          "i": 5,
          "lat": 27.59,
          "lon": 117.03
        },
        {
          "i": 6,
          "lat": 27.6,
          "lon": 116.8
        },
        {
          "i": 7,
          "lat": 27.59,
          "lon": 116.62
        },
        {
          "i": 8,
          "lat": 27.57,
          "lon": 116.46
        },
        {
          "i": 9,
          "lat": 27.54,
          "lon": 116.32
        },
        {
          "i": 10,
          "lat": 27.5,
          "lon": 116.19
        },
        {
          "i": 11,
          "lat": 27.45,
          "lon": 116.05
        },
        {
          "i": 12,
          "lat": 27.4,
          "lon": 115.9
        },
        {
          "i": 13,
          "lat": 27.34,
          "lon": 115.74
        },
        {
          "i": 14,
          "lat": 27.28,
          "lon": 115.58
        },
        {
          "i": 15,
          "lat": 27.21,
          "lon": 115.42
        },
        {
          "i": 16,
          "lat": 27.13,
          "lon": 115.25
        },
        {
          "i": 17,
          "lat": 27.06,
          "lon": 115.08
        },
        {
          "i": 18,
          "lat": 27.0,
          "lon": 114.9
        },
        {
          "i": 19,
          "lat": 26.95,
          "lon": 114.71
        },
        {
          "i": 20,
          "lat": 26.9,
          "lon": 114.51
        },
        {
          "i": 21,
          "lat": 26.86,
          "lon": 114.31
        },
        {
          "i": 22,
          "lat": 26.82,
          "lon": 114.11
        },
        {
          "i": 23,
          "lat": 26.77,
          "lon": 113.9
        },
        {
          "i": 24,
          "lat": 26.7,
          "lon": 113.7,
          "time": "2026-08-29T12:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 25,
          "lat": 26.61,
          "lon": 113.49
        },
        {
          "i": 26,
          "lat": 26.5,
          "lon": 113.26
        },
        {
          "i": 27,
          "lat": 26.38,
          "lon": 113.03
        },
        {
          "i": 28,
          "lat": 26.27,
          "lon": 112.81
        },
        {
          "i": 29,
          "lat": 26.17,
          "lon": 112.63
        },
        {
          "i": 30,
          "lat": 26.1,
          "lon": 112.5,
          "time": "2026-08-29T18:00:00+00:00",
          "intensity": "Low Pressure Area",
          "wind": "40km/h"
        }
      ]
    }
  ]
};
