/* hk_tctrack.js — GENERATED by scripts/ingest_tctrack.py. Do not edit by hand.
 * HKO updates TC forecast tracks 3-hourly (6-hourly for distant systems);
 * this file is refreshed every 30 minutes by Actions, commit-only-on-change.
 * storms: [] means HKO currently issues no forecast track — a real answer.
 * The page shows bulletinTime and generatedAt separately: staleness is
 * always visible, never hidden. */
const HK_TCTRACK = {
  "generatedAt": "2026-07-25T19:12:15+00:00",
  "source": "HKO tc_list.xml + hko_tctrack_{TCID}.xml on www.weather.gov.hk (no CORS headers; ingested every 30 min by GitHub Actions)",
  "storms": [
    {
      "id": "2617",
      "nameEn": "NOUL",
      "nameZh": "紅霞",
      "bulletinTime": "2026-07-26T03:00:22+08:00",
      "analysis": {
        "lat": 22.5,
        "lon": 115.0,
        "time": "2026-07-25T19:00:00+00:00",
        "intensity": "Severe Typhoon",
        "wind": "155km/h"
      },
      "past": [
        {
          "i": 1,
          "lat": 15.0,
          "lon": 130.2,
          "time": "2026-07-22T18:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 2,
          "lat": 15.7,
          "lon": 129.3,
          "time": "2026-07-23T00:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "55km/h"
        },
        {
          "i": 3,
          "lat": 17.1,
          "lon": 128.3,
          "time": "2026-07-23T06:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "55km/h"
        },
        {
          "i": 4,
          "lat": 17.4,
          "lon": 126.6,
          "time": "2026-07-23T12:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "55km/h"
        },
        {
          "i": 5,
          "lat": 17.9,
          "lon": 125.2,
          "time": "2026-07-23T18:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 6,
          "lat": 17.9,
          "lon": 124.4,
          "time": "2026-07-23T21:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 7,
          "lat": 18.3,
          "lon": 123.8,
          "time": "2026-07-24T00:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 8,
          "lat": 18.6,
          "lon": 122.9,
          "time": "2026-07-24T03:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "90km/h"
        },
        {
          "i": 9,
          "lat": 18.9,
          "lon": 121.7,
          "time": "2026-07-24T06:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "90km/h"
        },
        {
          "i": 10,
          "lat": 19.0,
          "lon": 121.2,
          "time": "2026-07-24T09:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "90km/h"
        },
        {
          "i": 11,
          "lat": 19.3,
          "lon": 120.4,
          "time": "2026-07-24T12:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "90km/h"
        },
        {
          "i": 12,
          "lat": 19.6,
          "lon": 120.0,
          "time": "2026-07-24T15:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "105km/h"
        },
        {
          "i": 13,
          "lat": 20.0,
          "lon": 119.4,
          "time": "2026-07-24T18:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "110km/h"
        },
        {
          "i": 14,
          "lat": 20.3,
          "lon": 118.7,
          "time": "2026-07-24T21:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "120km/h"
        },
        {
          "i": 15,
          "lat": 20.7,
          "lon": 118.1,
          "time": "2026-07-25T00:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "130km/h"
        },
        {
          "i": 16,
          "lat": 21.1,
          "lon": 117.3,
          "time": "2026-07-25T03:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 17,
          "lat": 21.4,
          "lon": 116.7,
          "time": "2026-07-25T06:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 18,
          "lat": 21.5,
          "lon": 116.4,
          "time": "2026-07-25T09:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 19,
          "lat": 21.8,
          "lon": 115.9,
          "time": "2026-07-25T12:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "140km/h"
        },
        {
          "i": 20,
          "lat": 21.9,
          "lon": 115.6,
          "time": "2026-07-25T15:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "145km/h"
        }
      ],
      "forecast": [
        {
          "i": 1,
          "lat": 22.71,
          "lon": 114.93
        },
        {
          "i": 2,
          "lat": 23.0,
          "lon": 114.8
        },
        {
          "i": 3,
          "lat": 23.11,
          "lon": 114.73
        },
        {
          "i": 4,
          "lat": 23.22,
          "lon": 114.65
        },
        {
          "i": 5,
          "lat": 23.34,
          "lon": 114.56
        },
        {
          "i": 6,
          "lat": 23.47,
          "lon": 114.46
        },
        {
          "i": 7,
          "lat": 23.59,
          "lon": 114.38
        },
        {
          "i": 8,
          "lat": 23.7,
          "lon": 114.3
        },
        {
          "i": 9,
          "lat": 23.8,
          "lon": 114.24
        },
        {
          "i": 10,
          "lat": 23.9,
          "lon": 114.18
        },
        {
          "i": 11,
          "lat": 23.99,
          "lon": 114.13
        },
        {
          "i": 12,
          "lat": 24.08,
          "lon": 114.09
        },
        {
          "i": 13,
          "lat": 24.18,
          "lon": 114.04
        },
        {
          "i": 14,
          "lat": 24.3,
          "lon": 114.0
        },
        {
          "i": 15,
          "lat": 24.43,
          "lon": 113.96
        },
        {
          "i": 16,
          "lat": 24.57,
          "lon": 113.93
        },
        {
          "i": 17,
          "lat": 24.71,
          "lon": 113.89
        },
        {
          "i": 18,
          "lat": 24.87,
          "lon": 113.86
        },
        {
          "i": 19,
          "lat": 25.03,
          "lon": 113.83
        },
        {
          "i": 20,
          "lat": 25.2,
          "lon": 113.8,
          "time": "2026-07-26T15:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 21,
          "lat": 25.39,
          "lon": 113.77
        },
        {
          "i": 22,
          "lat": 25.59,
          "lon": 113.74
        },
        {
          "i": 23,
          "lat": 25.81,
          "lon": 113.71
        },
        {
          "i": 24,
          "lat": 26.02,
          "lon": 113.68
        },
        {
          "i": 25,
          "lat": 26.22,
          "lon": 113.64
        },
        {
          "i": 26,
          "lat": 26.4,
          "lon": 113.6
        },
        {
          "i": 27,
          "lat": 26.56,
          "lon": 113.54
        },
        {
          "i": 28,
          "lat": 26.7,
          "lon": 113.47
        },
        {
          "i": 29,
          "lat": 26.84,
          "lon": 113.4
        },
        {
          "i": 30,
          "lat": 26.96,
          "lon": 113.33
        },
        {
          "i": 31,
          "lat": 27.08,
          "lon": 113.26
        },
        {
          "i": 32,
          "lat": 27.2,
          "lon": 113.2
        },
        {
          "i": 33,
          "lat": 27.31,
          "lon": 113.16
        },
        {
          "i": 34,
          "lat": 27.41,
          "lon": 113.12
        },
        {
          "i": 35,
          "lat": 27.5,
          "lon": 113.09
        },
        {
          "i": 36,
          "lat": 27.59,
          "lon": 113.07
        },
        {
          "i": 37,
          "lat": 27.69,
          "lon": 113.04
        },
        {
          "i": 38,
          "lat": 27.8,
          "lon": 113.0
        },
        {
          "i": 39,
          "lat": 27.93,
          "lon": 112.95
        },
        {
          "i": 40,
          "lat": 28.08,
          "lon": 112.9
        },
        {
          "i": 41,
          "lat": 28.24,
          "lon": 112.84
        },
        {
          "i": 42,
          "lat": 28.39,
          "lon": 112.78
        },
        {
          "i": 43,
          "lat": 28.51,
          "lon": 112.73
        },
        {
          "i": 44,
          "lat": 28.6,
          "lon": 112.7,
          "time": "2026-07-27T15:00:00+00:00",
          "intensity": "Low Pressure Area",
          "wind": "40km/h"
        }
      ]
    }
  ]
};
