/* hk_tctrack.js — GENERATED by scripts/ingest_tctrack.py. Do not edit by hand.
 * HKO updates TC forecast tracks 3-hourly (6-hourly for distant systems);
 * this file is refreshed every 30 minutes by Actions, commit-only-on-change.
 * storms: [] means HKO currently issues no forecast track — a real answer.
 * The page shows bulletinTime and generatedAt separately: staleness is
 * always visible, never hidden. */
const HK_TCTRACK = {
  "generatedAt": "2026-08-07T06:15:16+00:00",
  "source": "HKO tc_list.xml + hko_tctrack_{TCID}.xml on www.weather.gov.hk (no CORS headers; ingested every 30 min by GitHub Actions)",
  "storms": [
    {
      "id": "2618",
      "nameEn": "DOLPHIN",
      "nameZh": "白海豚",
      "bulletinTime": "2026-08-07T10:02:15+08:00",
      "analysis": {
        "lat": 27.2,
        "lon": 128.9,
        "time": "2026-08-07T00:00:00+00:00",
        "intensity": "Severe Typhoon",
        "wind": "165km/h"
      },
      "past": [
        {
          "i": 1,
          "lat": 24.0,
          "lon": 149.5,
          "time": "2026-08-02T18:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 2,
          "lat": 24.4,
          "lon": 148.5,
          "time": "2026-08-03T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 3,
          "lat": 24.9,
          "lon": 147.1,
          "time": "2026-08-03T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 4,
          "lat": 25.0,
          "lon": 145.6,
          "time": "2026-08-03T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 5,
          "lat": 25.2,
          "lon": 144.2,
          "time": "2026-08-03T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 6,
          "lat": 25.2,
          "lon": 143.2,
          "time": "2026-08-04T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 7,
          "lat": 25.2,
          "lon": 141.8,
          "time": "2026-08-04T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 8,
          "lat": 25.2,
          "lon": 140.5,
          "time": "2026-08-04T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 9,
          "lat": 25.3,
          "lon": 140.0,
          "time": "2026-08-04T15:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 10,
          "lat": 25.3,
          "lon": 139.3,
          "time": "2026-08-04T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 11,
          "lat": 25.4,
          "lon": 138.3,
          "time": "2026-08-05T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 12,
          "lat": 25.7,
          "lon": 137.3,
          "time": "2026-08-05T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 13,
          "lat": 26.0,
          "lon": 136.2,
          "time": "2026-08-05T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 14,
          "lat": 26.3,
          "lon": 135.1,
          "time": "2026-08-05T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 15,
          "lat": 26.3,
          "lon": 133.6,
          "time": "2026-08-06T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 16,
          "lat": 26.6,
          "lon": 132.6,
          "time": "2026-08-06T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 17,
          "lat": 26.5,
          "lon": 131.4,
          "time": "2026-08-06T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 18,
          "lat": 26.9,
          "lon": 130.3,
          "time": "2026-08-06T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        }
      ],
      "forecast": [
        {
          "i": 1,
          "lat": 27.19,
          "lon": 128.81
        },
        {
          "i": 2,
          "lat": 27.18,
          "lon": 128.7
        },
        {
          "i": 3,
          "lat": 27.16,
          "lon": 128.56
        },
        {
          "i": 4,
          "lat": 27.15,
          "lon": 128.41
        },
        {
          "i": 5,
          "lat": 27.13,
          "lon": 128.25
        },
        {
          "i": 6,
          "lat": 27.11,
          "lon": 128.08
        },
        {
          "i": 7,
          "lat": 27.09,
          "lon": 127.9
        },
        {
          "i": 8,
          "lat": 27.07,
          "lon": 127.72
        },
        {
          "i": 9,
          "lat": 27.05,
          "lon": 127.55
        },
        {
          "i": 10,
          "lat": 27.04,
          "lon": 127.39
        },
        {
          "i": 11,
          "lat": 27.02,
          "lon": 127.23
        },
        {
          "i": 12,
          "lat": 27.0,
          "lon": 127.1
        },
        {
          "i": 13,
          "lat": 26.98,
          "lon": 126.98
        },
        {
          "i": 14,
          "lat": 26.96,
          "lon": 126.86
        },
        {
          "i": 15,
          "lat": 26.94,
          "lon": 126.76
        },
        {
          "i": 16,
          "lat": 26.92,
          "lon": 126.65
        },
        {
          "i": 17,
          "lat": 26.9,
          "lon": 126.55
        },
        {
          "i": 18,
          "lat": 26.88,
          "lon": 126.46
        },
        {
          "i": 19,
          "lat": 26.86,
          "lon": 126.36
        },
        {
          "i": 20,
          "lat": 26.84,
          "lon": 126.27
        },
        {
          "i": 21,
          "lat": 26.83,
          "lon": 126.18
        },
        {
          "i": 22,
          "lat": 26.82,
          "lon": 126.09
        },
        {
          "i": 23,
          "lat": 26.81,
          "lon": 125.99
        },
        {
          "i": 24,
          "lat": 26.8,
          "lon": 125.9,
          "time": "2026-08-08T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 25,
          "lat": 26.8,
          "lon": 125.8
        },
        {
          "i": 26,
          "lat": 26.79,
          "lon": 125.71
        },
        {
          "i": 27,
          "lat": 26.79,
          "lon": 125.62
        },
        {
          "i": 28,
          "lat": 26.8,
          "lon": 125.53
        },
        {
          "i": 29,
          "lat": 26.8,
          "lon": 125.43
        },
        {
          "i": 30,
          "lat": 26.81,
          "lon": 125.34
        },
        {
          "i": 31,
          "lat": 26.81,
          "lon": 125.25
        },
        {
          "i": 32,
          "lat": 26.83,
          "lon": 125.16
        },
        {
          "i": 33,
          "lat": 26.84,
          "lon": 125.07
        },
        {
          "i": 34,
          "lat": 26.86,
          "lon": 124.98
        },
        {
          "i": 35,
          "lat": 26.88,
          "lon": 124.89
        },
        {
          "i": 36,
          "lat": 26.9,
          "lon": 124.8
        },
        {
          "i": 37,
          "lat": 26.93,
          "lon": 124.71
        },
        {
          "i": 38,
          "lat": 26.96,
          "lon": 124.62
        },
        {
          "i": 39,
          "lat": 27.0,
          "lon": 124.53
        },
        {
          "i": 40,
          "lat": 27.04,
          "lon": 124.44
        },
        {
          "i": 41,
          "lat": 27.09,
          "lon": 124.35
        },
        {
          "i": 42,
          "lat": 27.13,
          "lon": 124.26
        },
        {
          "i": 43,
          "lat": 27.18,
          "lon": 124.17
        },
        {
          "i": 44,
          "lat": 27.23,
          "lon": 124.08
        },
        {
          "i": 45,
          "lat": 27.27,
          "lon": 123.99
        },
        {
          "i": 46,
          "lat": 27.32,
          "lon": 123.89
        },
        {
          "i": 47,
          "lat": 27.36,
          "lon": 123.8
        },
        {
          "i": 48,
          "lat": 27.4,
          "lon": 123.7,
          "time": "2026-08-09T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 49,
          "lat": 27.44,
          "lon": 123.6
        },
        {
          "i": 50,
          "lat": 27.47,
          "lon": 123.5
        },
        {
          "i": 51,
          "lat": 27.5,
          "lon": 123.39
        },
        {
          "i": 52,
          "lat": 27.52,
          "lon": 123.29
        },
        {
          "i": 53,
          "lat": 27.55,
          "lon": 123.18
        },
        {
          "i": 54,
          "lat": 27.57,
          "lon": 123.08
        },
        {
          "i": 55,
          "lat": 27.6,
          "lon": 122.97
        },
        {
          "i": 56,
          "lat": 27.63,
          "lon": 122.86
        },
        {
          "i": 57,
          "lat": 27.67,
          "lon": 122.74
        },
        {
          "i": 58,
          "lat": 27.71,
          "lon": 122.63
        },
        {
          "i": 59,
          "lat": 27.75,
          "lon": 122.52
        },
        {
          "i": 60,
          "lat": 27.8,
          "lon": 122.4
        },
        {
          "i": 61,
          "lat": 27.86,
          "lon": 122.28
        },
        {
          "i": 62,
          "lat": 27.92,
          "lon": 122.16
        },
        {
          "i": 63,
          "lat": 27.99,
          "lon": 122.04
        },
        {
          "i": 64,
          "lat": 28.06,
          "lon": 121.91
        },
        {
          "i": 65,
          "lat": 28.13,
          "lon": 121.78
        },
        {
          "i": 66,
          "lat": 28.21,
          "lon": 121.66
        },
        {
          "i": 67,
          "lat": 28.29,
          "lon": 121.53
        },
        {
          "i": 68,
          "lat": 28.37,
          "lon": 121.4
        },
        {
          "i": 69,
          "lat": 28.45,
          "lon": 121.27
        },
        {
          "i": 70,
          "lat": 28.53,
          "lon": 121.15
        },
        {
          "i": 71,
          "lat": 28.62,
          "lon": 121.02
        },
        {
          "i": 72,
          "lat": 28.7,
          "lon": 120.9,
          "time": "2026-08-10T00:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "120km/h"
        },
        {
          "i": 73,
          "lat": 28.78,
          "lon": 120.78
        },
        {
          "i": 74,
          "lat": 28.87,
          "lon": 120.66
        },
        {
          "i": 75,
          "lat": 28.96,
          "lon": 120.55
        },
        {
          "i": 76,
          "lat": 29.06,
          "lon": 120.44
        },
        {
          "i": 77,
          "lat": 29.15,
          "lon": 120.32
        },
        {
          "i": 78,
          "lat": 29.24,
          "lon": 120.21
        },
        {
          "i": 79,
          "lat": 29.34,
          "lon": 120.1
        },
        {
          "i": 80,
          "lat": 29.43,
          "lon": 119.99
        },
        {
          "i": 81,
          "lat": 29.53,
          "lon": 119.87
        },
        {
          "i": 82,
          "lat": 29.62,
          "lon": 119.75
        },
        {
          "i": 83,
          "lat": 29.71,
          "lon": 119.63
        },
        {
          "i": 84,
          "lat": 29.8,
          "lon": 119.5
        },
        {
          "i": 85,
          "lat": 29.89,
          "lon": 119.37
        },
        {
          "i": 86,
          "lat": 29.98,
          "lon": 119.22
        },
        {
          "i": 87,
          "lat": 30.07,
          "lon": 119.07
        },
        {
          "i": 88,
          "lat": 30.17,
          "lon": 118.92
        },
        {
          "i": 89,
          "lat": 30.26,
          "lon": 118.76
        },
        {
          "i": 90,
          "lat": 30.35,
          "lon": 118.61
        },
        {
          "i": 91,
          "lat": 30.44,
          "lon": 118.45
        },
        {
          "i": 92,
          "lat": 30.52,
          "lon": 118.3
        },
        {
          "i": 93,
          "lat": 30.6,
          "lon": 118.16
        },
        {
          "i": 94,
          "lat": 30.68,
          "lon": 118.03
        },
        {
          "i": 95,
          "lat": 30.74,
          "lon": 117.91
        },
        {
          "i": 96,
          "lat": 30.8,
          "lon": 117.8,
          "time": "2026-08-11T00:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 97,
          "lat": 30.85,
          "lon": 117.71
        },
        {
          "i": 98,
          "lat": 30.89,
          "lon": 117.62
        },
        {
          "i": 99,
          "lat": 30.92,
          "lon": 117.55
        },
        {
          "i": 100,
          "lat": 30.95,
          "lon": 117.49
        },
        {
          "i": 101,
          "lat": 30.97,
          "lon": 117.43
        },
        {
          "i": 102,
          "lat": 30.99,
          "lon": 117.38
        },
        {
          "i": 103,
          "lat": 31.01,
          "lon": 117.33
        },
        {
          "i": 104,
          "lat": 31.03,
          "lon": 117.28
        },
        {
          "i": 105,
          "lat": 31.04,
          "lon": 117.24
        },
        {
          "i": 106,
          "lat": 31.06,
          "lon": 117.19
        },
        {
          "i": 107,
          "lat": 31.08,
          "lon": 117.15
        },
        {
          "i": 108,
          "lat": 31.1,
          "lon": 117.1
        },
        {
          "i": 109,
          "lat": 31.13,
          "lon": 117.05
        },
        {
          "i": 110,
          "lat": 31.15,
          "lon": 117.0
        },
        {
          "i": 111,
          "lat": 31.18,
          "lon": 116.95
        },
        {
          "i": 112,
          "lat": 31.21,
          "lon": 116.9
        },
        {
          "i": 113,
          "lat": 31.24,
          "lon": 116.85
        },
        {
          "i": 114,
          "lat": 31.27,
          "lon": 116.81
        },
        {
          "i": 115,
          "lat": 31.3,
          "lon": 116.76
        },
        {
          "i": 116,
          "lat": 31.32,
          "lon": 116.72
        },
        {
          "i": 117,
          "lat": 31.35,
          "lon": 116.69
        },
        {
          "i": 118,
          "lat": 31.37,
          "lon": 116.65
        },
        {
          "i": 119,
          "lat": 31.39,
          "lon": 116.62
        },
        {
          "i": 120,
          "lat": 31.4,
          "lon": 116.6,
          "time": "2026-08-12T00:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        }
      ]
    },
    {
      "id": "2621",
      "nameEn": "KUJIRA",
      "nameZh": "鯨魚",
      "bulletinTime": "2026-08-06T18:30:26+08:00",
      "analysis": {
        "lat": 16.7,
        "lon": 123.1,
        "time": "2026-08-06T09:00:00+00:00",
        "intensity": "Low Pressure Area",
        "wind": "40km/h"
      },
      "past": [
        {
          "i": 1,
          "lat": 17.4,
          "lon": 119.4,
          "time": "2026-08-04T09:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 2,
          "lat": 17.2,
          "lon": 119.2,
          "time": "2026-08-04T12:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 3,
          "lat": 17.0,
          "lon": 119.1,
          "time": "2026-08-04T15:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "55km/h"
        },
        {
          "i": 4,
          "lat": 17.0,
          "lon": 119.0,
          "time": "2026-08-04T18:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 5,
          "lat": 17.1,
          "lon": 119.0,
          "time": "2026-08-04T21:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 6,
          "lat": 17.2,
          "lon": 119.1,
          "time": "2026-08-05T00:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 7,
          "lat": 17.3,
          "lon": 119.2,
          "time": "2026-08-05T03:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 8,
          "lat": 17.5,
          "lon": 119.2,
          "time": "2026-08-05T06:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 9,
          "lat": 17.5,
          "lon": 119.3,
          "time": "2026-08-05T09:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 10,
          "lat": 17.5,
          "lon": 119.4,
          "time": "2026-08-05T12:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 11,
          "lat": 17.8,
          "lon": 119.9,
          "time": "2026-08-05T15:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 12,
          "lat": 17.7,
          "lon": 120.1,
          "time": "2026-08-05T18:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 13,
          "lat": 17.6,
          "lon": 120.5,
          "time": "2026-08-05T21:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 14,
          "lat": 17.6,
          "lon": 120.7,
          "time": "2026-08-06T00:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "55km/h"
        },
        {
          "i": 15,
          "lat": 17.2,
          "lon": 121.2,
          "time": "2026-08-06T03:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 16,
          "lat": 16.9,
          "lon": 122.3,
          "time": "2026-08-06T06:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        }
      ],
      "forecast": []
    }
  ]
};
