/* hk_uv.js — GENERATED by scripts/ingest_uv.py. Do not edit by hand.
 * HKO publishes a 15-minute mean UV index 07:00-18:00 HKT and blocks
 * direct browser fetches (no CORS headers on any of its UV files), so
 * Actions ingests it. The page shows the record time and the averaging
 * basis, and falls back to rhrread's hourly mean if this copy ages out. */
const HK_UV = {
  "generatedAt": "2026-09-23T01:35:19+00:00",
  "recordTime": "2026-09-23T09:30:00+08:00",
  "value": 1,
  "desc": "Low",
  "station": "King's Park",
  "basis": "15-minute mean",
  "source": "HKO open data latest_15min_uvindex.csv (CORS-locked; ingested every 15 min by GitHub Actions, 07:00-18:00 HKT)",
  "curve": [["07:00",0.1],["07:15",0.1],["07:30",0.2],["07:45",0.3],["08:00",0.5],["08:15",1],["08:30",1],["08:45",0.8],["09:00",1],["09:15",1],["09:30",1]]
};
