/* hk_uv.js — GENERATED by scripts/ingest_uv.py. Do not edit by hand.
 * HKO publishes a 15-minute mean UV index 07:00-18:00 HKT and blocks
 * direct browser fetches (no CORS headers on any of its UV files), so
 * Actions ingests it. The page shows the record time and the averaging
 * basis, and falls back to rhrread's hourly mean if this copy ages out. */
const HK_UV = {
  "generatedAt": "2026-09-14T05:29:16+00:00",
  "recordTime": "2026-09-14T13:15:00+08:00",
  "value": 3,
  "desc": "Moderate",
  "station": "King's Park",
  "basis": "15-minute mean",
  "source": "HKO open data latest_15min_uvindex.csv (CORS-locked; ingested every 15 min by GitHub Actions, 07:00-18:00 HKT)",
  "curve": [["07:00",0.1],["07:15",0.2],["07:30",0.4],["07:45",0.6],["08:00",0.7],["08:15",0.6],["08:30",1],["08:45",1],["09:00",1],["09:15",1],["09:30",2],["09:45",3],["10:00",4],["10:15",3],["10:30",2],["10:45",1],["11:00",2],["11:15",1],["11:30",1],["11:45",1],["12:00",1],["12:15",2],["12:30",3],["12:45",5],["13:00",5],["13:15",3]]
};
