#!/usr/bin/env python3
"""ingest_aqhi.py — fetch Hong Kong AQHI and write hk_aqhi.js.

Why this exists: the EPD AQHI feeds send CORS headers locked to
aqhi.gov.hk, so a static page cannot fetch them live. AQHI is published
hourly, and an hourly GitHub Actions run matches that cadence exactly —
the data file is at most one publication cycle behind the source, and the
page displays the record time so staleness is always visible.

Output is a <script>-tag data file (the Atlas's standard pattern):
    const HK_AQHI = { generatedAt, recordTime, stations: [
        {name, type, aqhi, risk}, ... ] };

Commit-only-on-change: compare everything EXCEPT generatedAt, so a run
that fetched identical data produces no commit (see workflow).
"""
from __future__ import annotations

import json
import re
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

FEED = "https://www.aqhi.gov.hk/epd/ddata/html/out/aqhi_ind_rss_Eng.xml"
OUT = Path(__file__).resolve().parent.parent / "hk_aqhi.js"

# description format: "Central/Western - General Stations: 2 Low - Tue, 14 Jul 2026 00:30"
DESC_RE = re.compile(
    r"^(?P<name>.+?) - (?P<type>General Stations|Roadside Stations): "
    r"(?P<aqhi>\d+\+?|-) ?(?P<risk>Low|Moderate|High|Very High|Serious|)"
    r" - (?P<time>.+)$"
)


def main() -> int:
    req = urllib.request.Request(FEED, headers={"User-Agent": "hk-weather-atlas-aqhi-ingest"})
    xml = urllib.request.urlopen(req, timeout=20).read().decode("utf-8", "replace")

    stations, record_time = [], None
    for item in re.findall(r"<item>(.*?)</item>", xml, re.S):
        m = re.search(r"<!\[CDATA\[(.*?)\]\]>", item, re.S)
        if not m:
            continue
        d = DESC_RE.match(m.group(1).strip())
        if not d:
            print(f"WARN: unparsed item: {m.group(1)[:80]!r}", file=sys.stderr)
            continue
        record_time = d.group("time")
        stations.append({
            "name": d.group("name"),
            "type": "roadside" if "Roadside" in d.group("type") else "general",
            "aqhi": d.group("aqhi"),
            "risk": d.group("risk") or "unavailable",
        })

    if len(stations) < 10:
        print(f"FAIL: only {len(stations)} stations parsed — feed format may have changed", file=sys.stderr)
        return 1

    payload = {
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "recordTime": record_time,
        "source": "EPD aqhi.gov.hk RSS (CORS-locked; ingested hourly by GitHub Actions)",
        "stations": stations,
    }
    OUT.write_text(
        "/* hk_aqhi.js — GENERATED by scripts/ingest_aqhi.py. Do not edit by hand.\n"
        " * EPD publishes AQHI hourly; this file is refreshed hourly by Actions.\n"
        " * The page shows recordTime so any staleness is visible, never hidden. */\n"
        f"const HK_AQHI = {json.dumps(payload, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"OK: {len(stations)} stations, record time {record_time}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
